---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://faas-fra1-afec6ce7.doserverless.co/api/v1/web/fn-97f69b9b-30c7-41dd-947b-f687dbc54ade/default/webcal?url={{ url }}
polling_headers: ''
polling_body: ''
id: 130376
custom_fields:
- keyname: url
  field_type: url
  name: URL of Calendar
  placeholder: https://example.com/calendar.ics
  help_text: Replace webcal:// with https:// if needed.
name: Monthly Events
refresh_interval: 15
