---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://argoroots-public.s3.eu-central-1.amazonaws.com/borsihind/{{ plan }}.json
polling_headers: ''
polling_body: ''
id: 122983
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  description: Display real-time Estonian electricity prices from börsihind.ee on your TRMNL screen. View current pricing in cents per kWh, find the cheapest 1-4 hour periods for optimal energy usage, and see hourly price trends. Complete breakdown includes electricity price, transmission costs, renewable energy fees, and excise tax.
  github_url: https://github.com/argoroots/trmnl
  learn_more_url: https://www.borsihind.ee
  email_address: argo@roots.ee
- keyname: plan
  field_type: select
  name: Pricing plan
  description: Select your Elektrilevi network pricing plan. Each plan has different transmission rates that affect your total electricity cost.
  default: V1
  optional: false
  options:
  - Võrk 1: V1
  - Võrk 2: V2
  - Võrk 4: V4
  - Võrk 5: V5
- keyname: margin
  field_type: number
  name: Seller Margin
  description: Set the margin (cents/kWh) that your electricity seller adds to the base price. This is used to calculate the total cost of electricity.
  default: 0
- keyname: timespan
  field_type: select
  name: Highlighted timespan
  description: Choose which cheapest hour period to highlight with special styling on the display.
  optional: true
  options:
  - 1 hour: 1
  - 2 hours: 2
  - 3 hours: 3
  - 4 hours: 4
name: Börsihind.ee
refresh_interval: 15
